server:
  port: 18050
  
spring: 
  application:
    name: config
  cloud:
    config: 
      server: 
        git: 
          uri: youuri
          search-paths: SpringCloudProjectConfigs
          username: yourname
          password: yourpassword
        default-label: dev
  rabbitmq:
    host: 59.110.239.164
    port: 5673
    username: guest
    password: guest
    
  security: 
    user:
      name: admin
      password: mypass

eureka: 
  instance:
    hostname: localhost
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client: 
    region: javadevmap
    availability-zones: 
      javadevmap: map_eureka
    service-url: 
      map_eureka: http://admin:mypass@localhost:18001/eureka/
      
management:
  endpoints: 
    web:
      exposure: 
        include:
        - shutdown
        - info
        - health
        - bus-refresh

  endpoint:
    shutdown:
      enabled: true
    bus-refresh:
      enabled: true
      
info:
  author: hw
  project: config service demo