server:
  port: 18030
spring:
  application:
    name: Turbine
    
eureka: 
  instance:
    hostname: localhost
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    metadata-map: 
      cluster: main
  client: 
    region: javadevmap
    availability-zones: 
      javadevmap: map_eureka
    service-url: 
      map_eureka: http://admin:mypass@localhost:18001/eureka/
      
turbine:
  app-config: COMMON-SERVICE,ACCESSLAYER
  aggregator: 
    clusterConfig: main
  clusterNameExpression: metadata['cluster']
  combine-host-port: true
  
    
management:
  endpoints: 
    web:
      exposure: 
        include:
        - shutdown
        - info
        - health

  endpoint:
    shutdown:
      enabled: true
      
info:
  author: hw
  project: turbine demo