server:
  port: 18010
spring:
  application:
    name: common-service
  rabbitmq:
    host: 59.110.239.164
    port: 5673
    username: guest
    password: guest
  sleuth:
    enabled: true
    trace-id128: true
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    #注意观察rabbitmq，如果没有生成zipkin队列，要手动生成此队列
    sender:
      type: rabbit
#   web mode: 
#       zipkin server commond:curl -sSL https://zipkin.io/quickstart.sh | bash -s
#                             java -jar zipkin.jar
#    sender:
#      type: web
#    enabled: true
#    base-url: http://59.110.239.164:9411 # 指定了 Zipkin 服务器的地址
    
eureka: 
  instance:
    hostname: localhost
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    metadata-map: 
      cluster: main
  client: 
    region: javadevmap
    availability-zones: 
      javadevmap: map_eureka
    service-url: 
      map_eureka: http://admin:mypass@localhost:18001/eureka/
      
  
hystrix:    
  threadpool:  
    default:  
      coreSize: 100
  command: 
    default: 
      execution: 
        isolation: 
          thread:
            timeoutInMilliseconds: 2000      

management:
  endpoints: 
    web:
      exposure: 
        include:
        - shutdown
        - info
        - health

  endpoint:
    shutdown:
      enabled: true
      
info:
  author: hw
  project: common service demo